# Generated by Django 2.1.3 on 2018-11-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_addr', models.GenericIPAddressField()),
                ('remote_user', models.CharField(max_length=50, null=True)),
                ('time_local', models.DateTimeField()),
                ('request_time', models.DecimalField(decimal_places=3, max_digits=8)),
                ('host', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('status', models.IntegerField()),
                ('bytes_sent', models.IntegerField()),
                ('http_referer', models.URLField()),
                ('request_length', models.IntegerField()),
                ('body_bytes_sent', models.IntegerField()),
                ('http_user_agent', models.CharField(max_length=100)),
            ],
        ),
    ]
