# Generated by Django 2.2 on 2019-06-11 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_nginx_access', '0002_auto_20190610_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlsagg',
            options={'verbose_name_plural': 'Агрегация урлов'},
        ),
        migrations.AlterModelOptions(
            name='urlsdictionary',
            options={'verbose_name_plural': 'Справочник урлов'},
        ),
        migrations.AlterModelOptions(
            name='useragentsagg',
            options={'verbose_name_plural': 'Агрегация юзер-агентов'},
        ),
        migrations.AlterModelOptions(
            name='useragentsdictionary',
            options={'verbose_name_plural': 'Юзер-агенты'},
        ),
    ]
