# Generated by Django 2.2 on 2019-06-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_nginx_access', '0003_auto_20190611_0643'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='logitem',
            index=models.Index(fields=['-time_local'], name='django_ngin_time_lo_73f342_idx'),
        ),
    ]
