# Generated by Django 2.2 on 2019-06-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_nginx_access', '0004_auto_20190612_0733'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='urlsagg',
            index=models.Index(fields=['agg_month', 'url'], name='django_ngin_agg_mon_8b2ce4_idx'),
        ),
    ]
