# Generated by Django 2.2 on 2019-06-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_nginx_access', '0005_auto_20190612_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useragentsdictionary',
            options={'verbose_name_plural': 'Справочник юзер-агенты'},
        ),
        migrations.RemoveIndex(
            model_name='urlsagg',
            name='django_ngin_agg_mon_8b2ce4_idx',
        ),
        migrations.AddConstraint(
            model_name='urlsagg',
            constraint=models.UniqueConstraint(fields=('agg_month', 'url'), name='agg_month_url_uniq'),
        ),
    ]
