# Generated by Django 2.2 on 2019-06-13 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_nginx_access', '0006_auto_20190612_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefererDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referer', models.URLField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Справочник откуда пришли',
            },
        ),
        migrations.AlterField(
            model_name='urlsdictionary',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='useragentsdictionary',
            name='user_agent',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='RefererAgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agg_month', models.DateField()),
                ('amount', models.IntegerField()),
                ('referer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_nginx_access.RefererDictionary')),
            ],
            options={
                'verbose_name_plural': 'Агрегация откуда пришли',
            },
        ),
    ]
