# Generated by Django 2.2.3 on 2019-09-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_nginx_access', '0007_auto_20190613_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragentsdictionary',
            name='user_agent',
            field=models.TextField(unique=True),
        ),
    ]
